cluster_setup:
  rivanna-a100:
    card_name: a100
    num_cpus: 6
    num_gpus: 1
    time: 05:00:00
  rivanna-k80:
    card_name: k80
    num_cpus: 6
    num_gpus: 1
    time: '12:00:00'
  rivanna-p100:
    card_name: p100
    num_cpus: 6
    num_gpus: 1
    time: 06:00:00
  rivanna-rtx2080:
    card_name: rtx2080
    num_cpus: 6
    num_gpus: 1
    time: 06:00:00
  rivanna-rtx3090:
    card_name: rtx3090
    num_cpus: 6
    num_gpus: 1
    time: 06:00:00
  rivanna-v100:
    card_name: v100
    num_cpus: 6
    num_gpus: 1
    time: 06:00:00
model_parameters:
  DLAnalysisOnly: 'False'
  DLRestorefromcheckpoint: 'False'
  DLinputCheckpointpostfix: '1'
  TFTTransformerepochs: 20
  debugging_set_log_device_placement: 'False'
  set_soft_device_placement: 'False'
user:
  account: ds6011-sp22-002
  runpath: /project/ds6011-sp22-002/runner/mlcommons
